 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cats", type: :request do
  
  # Cat. As you add validations to Cat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cat.create! valid_attributes
      get cats_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cat = Cat.create! valid_attributes
      get cat_url(cat)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cat_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cat = Cat.create! valid_attributes
      get edit_cat_url(cat)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cat" do
        expect {
          post cats_url, params: { cat: valid_attributes }
        }.to change(Cat, :count).by(1)
      end

      it "redirects to the created cat" do
        post cats_url, params: { cat: valid_attributes }
        expect(response).to redirect_to(cat_url(Cat.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cat" do
        expect {
          post cats_url, params: { cat: invalid_attributes }
        }.to change(Cat, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cats_url, params: { cat: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cat" do
        cat = Cat.create! valid_attributes
        patch cat_url(cat), params: { cat: new_attributes }
        cat.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cat" do
        cat = Cat.create! valid_attributes
        patch cat_url(cat), params: { cat: new_attributes }
        cat.reload
        expect(response).to redirect_to(cat_url(cat))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cat = Cat.create! valid_attributes
        patch cat_url(cat), params: { cat: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cat" do
      cat = Cat.create! valid_attributes
      expect {
        delete cat_url(cat)
      }.to change(Cat, :count).by(-1)
    end

    it "redirects to the cats list" do
      cat = Cat.create! valid_attributes
      delete cat_url(cat)
      expect(response).to redirect_to(cats_url)
    end
  end
end
